[package]
name = "aoc22"
description = "My Advent of Code 2022 solutions"
authors = ["NotNite <hi@notnite.com>"]
version = "0.1.0"
edition = "2021"

[dependencies]
# Day 3, 4, 5
itertools = "0.10.5"

# Day 7
vfs = "0.8.0"

# Day 12
pathfinding = "4.0.0"
